name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Organize Folders
        run: |
          mkdir -p src/main/resources
          mkdir -p src/main/java/com/mymod
          [ -f fabric.mod.json ] && mv fabric.mod.json src/main/resources/
          [ -f MainMod.java ] && mv MainMod.java src/main/java/com/mymod/
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle Wrapper
        run: gradle wrapper
        
      - name: Build Mod
        run: ./gradlew build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Jar
          path: build/libs/*.jar
